<?php
defined('XOOPS_ROOT_PATH') || die('XOOPS root path not defined');

$module_handler = xoops_gethandler('module');
$module = $module_handler->getByDirname(basename(dirname(dirname(__FILE__))));
$pathIcon32 = '../../' . $module->getInfo('icons32');
//$pathIcon32 = '/assets/images/icons/32x32';

xoops_loadLanguage('modinfo', $module->dirname());

$adminmenu = array();
$i = 0;
$adminmenu[$i]['title'] = _MAIN;
$adminmenu[$i]['link'] = "admin/index.php";
$adminmenu[$i]['icon'] = $pathIcon32 . '/home.png';
$adminmenu[$i]['icon_small'] = "assets/images/topics32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_ADMENU2;
$adminmenu[$i]['link'] = "admin/index.php?op=topicsmanager";
$adminmenu[$i]['icon'] = "assets/images/topics32.png";
$adminmenu[$i]['icon_small'] = "assets/images/topics32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_ADMENU3;
$adminmenu[$i]['link'] = "admin/index.php?op=newarticle";
$adminmenu[$i]['icon'] = "assets/images/newarticle32.png";
$adminmenu[$i]['icon_small'] = "assets/images/newarticle32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_GROUPPERMS;
$adminmenu[$i]['link'] = "admin/permissions.php";
$adminmenu[$i]['icon'] = $pathIcon32 . '/permissions.png';
$adminmenu[$i]['icon_small'] = $pathIcon32 . '/permissions.png';
++$i;
$adminmenu[$i]['title'] = _MI_NW_PRUNENEWS;
$adminmenu[$i]['link'] = "admin/prune.php";
$adminmenu[$i]['icon'] = "assets/images/prune32.png";
$adminmenu[$i]['icon_small'] = "assets/images/prune32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_EXPORT;
$adminmenu[$i]['link'] = "admin/export.php";
$adminmenu[$i]['icon'] = "assets/images/export32.png";
$adminmenu[$i]['icon_small'] = "assets/images/export32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_STATS;
$adminmenu[$i]['link'] = "admin/stats.php";
$adminmenu[$i]['icon'] = "assets/images/stats32.png";
$adminmenu[$i]['icon_small'] = "assets/images/stats32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_NEWSLETTER;
$adminmenu[$i]['link'] = "admin/newsletter.php";
$adminmenu[$i]['icon'] = "assets/images/newsletter32.png";
$adminmenu[$i]['icon_small'] = "assets/images/newsletter32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_METAGEN;
$adminmenu[$i]['link'] = "admin/metagen.php";
$adminmenu[$i]['icon'] = "assets/images/metagen32.png";
$adminmenu[$i]['icon_small'] = "assets/images/metagen32.png";
++$i;
$adminmenu[$i]['title'] = _MI_NW_CLONER;
$adminmenu[$i]['link'] = "admin/clone.php";
$adminmenu[$i]['icon'] = "assets/images/cloner32.png";
$adminmenu[$i]['icon_small'] = "assets/images/cloner32.png";
