<?php

$cfg = [];
// How many items do you want to display in the Summary table visible in the article's page ?
$cfg['article_summary_items_count'] = (null !== $helper->getConfig('storyhome')) ? $helper->getConfig('storyhome') : 10;

// Auto generate meta keywords ?
$cfg['meta_keywords_auto_generate'] = true;

// Number of meta keywords generated by the module (it's just a default value)
$cfg['meta_keywords_count'] = 20;

// Default's order of keywords (it's just a default value)
$cfg['meta_keywords_order'] = 0;

// Does the module searches inside its own comments ?
$cfg['config_search_comments'] = true;

// Only enable registred users to rate news ?
$cfg['config_rating_registred_only'] = false;

// Maximum number of users before to replace the users list with a simple text box where you have to type the author's ID ?
$cfg['config_max_users_list'] = 300;

// Use the "fun" menu for the module's administration ?
$cfg['use_fun_menu'] = false;

// Create a clickable path from the root to the current topic (if we are viewing a topic) ?
$cfg['create_clickable_path'] = false;
